package view.mapsimulation;

import java.util.List;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseButton;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Paint;
import javax.swing.DefaultComboBoxModel;
import model.routes.Flow;
import model.topology.Lane;
import view.MogenView;
import view.mapelements.VehicleTypePanel;

/**
 *
 * @author Neblis
 */
public class FlowFrame extends javax.swing.JFrame implements MapMouseEvent {

    /**
     * Creates new form FlowFrame
     */
    private final static String TITLE = "Add new vehicle Flow";
    private final static String ADD = "Add";
    
    private final static String DESTINATION = "Destination";
    private final static String ORIGIN = "Origin";
    private final static String BEGIN = "Begin (s)";
    private final static String END = "End (s)";
    private final static String TYPE = "Vehicle type";
    private final static String NUMBER = "Number";
    
    private final static String SELECTED_LANE_COLOR2 = "BLUE";
    
    private final static String NOT_SELECTED_LANE_ERROR = "Mest select both a "
                            + "destination and an origin for the vehicle flow";
    private final static String VARIABLES_NOT_SET_ERROR = "All values must be set";
    private final static String TIME_ERROR = "Ending time can´t be lower the "
                            + "begining time";
    
    private final static String INFO = "Left click: select origin lane \n"
                            + "Right click: select destination lane";
    
    private Lane selectedLaneOrigin, selectedLaneDestination;
    private final MogenView view;
    private static DefaultComboBoxModel boxModel;
           
    private final DoubleProperty zoomProperty = new SimpleDoubleProperty(1.0d);
    private final DoubleProperty deltaY = new SimpleDoubleProperty(0.0d);
    private ScrollPane scrollPane = new ScrollPane();
    
    private int mouseStartX;         
    private int mouseStartY; 
    
    public FlowFrame(MogenView view, MapPanel map, List<VehicleTypePanel> VehicleTypes) {
        this.view = view;
        this.boxModel = new DefaultComboBoxModel<>(VehicleTypes.toArray());
        
        initComponents();
        this.setLocationRelativeTo(view);
        
        mapView.add(map);
        //map.addScrollListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        ODInfoPanel = new javax.swing.JPanel();
        originLabel = new javax.swing.JLabel();
        originInfoLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        destinationInfoLabel = new javax.swing.JLabel();
        optionsPanel = new javax.swing.JPanel();
        adddButton = new javax.swing.JButton();
        beginLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        beginTextField = new javax.swing.JFormattedTextField();
        endTextField = new javax.swing.JFormattedTextField();
        numberTextField = new javax.swing.JFormattedTextField();
        typeBox = new javax.swing.JComboBox<>();
        infoTextArea = new javax.swing.JTextArea();
        mapView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(TITLE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ODInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        originLabel.setFont(view.getFont());
        originLabel.setText(ORIGIN);

        originInfoLabel.setFont(view.getFont());

        destinationLabel.setFont(view.getFont());
        destinationLabel.setText(DESTINATION);

        destinationInfoLabel.setFont(view.getFont());

        javax.swing.GroupLayout ODInfoPanelLayout = new javax.swing.GroupLayout(ODInfoPanel);
        ODInfoPanel.setLayout(ODInfoPanelLayout);
        ODInfoPanelLayout.setHorizontalGroup(
            ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ODInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(destinationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(originLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ODInfoPanelLayout.setVerticalGroup(
            ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ODInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originLabel)
                    .addComponent(originInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ODInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destinationInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        optionsPanel.setBackground(new java.awt.Color(255, 255, 255));

        adddButton.setFont(view.getFont());
        adddButton.setText(ADD);
        adddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddButtonActionPerformed(evt);
            }
        });

        beginLabel.setFont(view.getFont());
        beginLabel.setText(BEGIN);

        endLabel.setFont(view.getFont());
        endLabel.setText(END);

        numberLabel.setFont(view.getFont());
        numberLabel.setText(NUMBER);

        typeLabel.setFont(view.getFont());
        typeLabel.setText(TYPE);

        beginTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        beginTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        beginTextField.setFont(view.getFont());

        endTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        endTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        endTextField.setFont(view.getFont());

        numberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numberTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numberTextField.setFont(view.getFont());

        typeBox.setFont(view.getFont());
        typeBox.setModel(boxModel);
        typeBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                        .addGap(0, 125, Short.MAX_VALUE)
                        .addComponent(adddButton))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(endLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(numberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(beginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(beginTextField)
                            .addComponent(endTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberTextField)
                            .addComponent(typeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beginTextField)
                    .addComponent(beginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126)
                .addComponent(adddButton)
                .addContainerGap())
        );

        infoTextArea.setColumns(20);
        infoTextArea.setFont(view.getFont());
        infoTextArea.setRows(5);
        infoTextArea.setText(INFO);
        infoTextArea.setAlignmentX(1.0F);
        infoTextArea.setAlignmentY(1.0F);
        infoTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mapView.setPreferredSize(new java.awt.Dimension(576, 576));
        mapView.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(separator)
                    .addComponent(ODInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoTextArea))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapView, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ODInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(infoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddButtonActionPerformed
        // TODO add your handling code here:
        if (selectedLaneOrigin == null || selectedLaneDestination == null){
            view.error(NOT_SELECTED_LANE_ERROR);
        }else if (beginTextField.getText().isEmpty() || endTextField.getText().isEmpty()
                || numberTextField.getText().isEmpty()){
            view.error(VARIABLES_NOT_SET_ERROR);
        }else if (Integer.parseInt(beginTextField.getText()) > 
                  Integer.parseInt(endTextField.getText())){
            view.error(TIME_ERROR);
        }else{
            Flow flow = new Flow(Integer.parseInt(beginTextField.getText()),
                   Integer.parseInt(endTextField.getText()), 
                   selectedLaneOrigin.getName(), selectedLaneDestination.getName(), 
                   typeBox.getSelectedItem().toString(), 
                   Integer.parseInt(numberTextField.getText()));
           
            view.addFlow(flow);
            
            unselectLanes();
            //this.dispose();
        }
            
    }//GEN-LAST:event_adddButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        unselectLanes();
    }//GEN-LAST:event_formWindowClosing
    
    
    @Override
    public void unselectLanes(){
        if (selectedLaneOrigin != null) selectedLaneOrigin.getPolyline().setStroke
                                        (Paint.valueOf(UNSELECTED_LANE_COLOR));
        if (selectedLaneDestination != null) selectedLaneDestination.getPolyline().setStroke
                                        (Paint.valueOf(UNSELECTED_LANE_COLOR));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ODInfoPanel;
    private javax.swing.JButton adddButton;
    private javax.swing.JLabel beginLabel;
    private javax.swing.JFormattedTextField beginTextField;
    private javax.swing.JLabel destinationInfoLabel;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel endLabel;
    private javax.swing.JFormattedTextField endTextField;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel mapView;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JFormattedTextField numberTextField;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JLabel originInfoLabel;
    private javax.swing.JLabel originLabel;
    private javax.swing.JSeparator separator;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addFunctionToLanes(Lane lane, MouseEvent e) {
        MouseButton button = e.getButton();
        if (button == MouseButton.PRIMARY){
            if(this.selectedLaneOrigin != null){
                this.selectedLaneOrigin.getPolyline().setStroke(Paint.valueOf(UNSELECTED_LANE_COLOR));
            }
            
            lane.getPolyline().setStroke(Paint.valueOf(SELECTED_LANE_COLOR));
            this.selectedLaneOrigin = lane;
            originInfoLabel.setText(selectedLaneOrigin.getName());
            
        } else if (button == MouseButton.SECONDARY){
            if(this.selectedLaneDestination != null){
                this.selectedLaneDestination.getPolyline().setStroke(Paint.valueOf(UNSELECTED_LANE_COLOR));
            }
            
            lane.getPolyline().setStroke(Paint.valueOf(SELECTED_LANE_COLOR2));
            this.selectedLaneDestination = lane;
            destinationInfoLabel.setText(selectedLaneDestination.getName());
        }
        System.out.println(lane.toString()); 
    }
}
