package view;

import javax.swing.JFileChooser;

/**
 *
 * @author darkm
 */
public class Settings extends javax.swing.JFrame {

    private final static String PYTHON2 = "Python 2 command:";
    private final static String SUMO = "Sumo location:";
    
    private final static String SAVE = "Save";
    
    private String sumo;
    private String python;
    private final MogenView view;
    
    private boolean changed = false;
    /**
     * Creates new form Settings
     * @param view
     * @param sumo
     * @param python
     */
    public Settings(MogenView view, String sumo, String python) {
        this.view = view;
        this.sumo = sumo;
        this.python = python;
        
        initComponents();
        this.setLocationRelativeTo(view);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pythonLabel = new javax.swing.JLabel();
        sumoLabel = new javax.swing.JLabel();
        pythonField = new javax.swing.JTextField();
        sumoField = new javax.swing.JTextField();
        searchIcon = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pythonLabel.setFont(view.getFont());
        pythonLabel.setText(PYTHON2);

        sumoLabel.setFont(view.getFont());
        sumoLabel.setText(SUMO);

        pythonField.setFont(view.getFont());
        pythonField.setText(python);
        pythonField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pythonFieldFocusLost(evt);
            }
        });

        sumoField.setFont(view.getFont());
        sumoField.setText(sumo);
        sumoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sumoFieldFocusLost(evt);
            }
        });

        searchIcon.setText("jLabel1");
        searchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sumoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pythonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pythonField)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(sumoField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pythonLabel)
                    .addComponent(pythonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumoField)
                            .addComponent(sumoLabel))
                        .addContainerGap())
                    .addComponent(searchIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        saveButton.setFont(view.getFont());
        saveButton.setText(SAVE);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (changed) view.changeSettings(python, sumo);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void pythonFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pythonFieldFocusLost
        // TODO add your handling code here:
        changed = true;
        python = pythonField.getText();
    }//GEN-LAST:event_pythonFieldFocusLost

    private void sumoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sumoFieldFocusLost
        // TODO add your handling code here:
        changed = true;
        sumo = sumoField.getText();
    }//GEN-LAST:event_sumoFieldFocusLost

    private void searchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchIconMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            sumo = chooser.getSelectedFile().getAbsolutePath();
            sumoField.setText(sumo);
        }
    }//GEN-LAST:event_searchIconMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField pythonField;
    private javax.swing.JLabel pythonLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JTextField sumoField;
    private javax.swing.JLabel sumoLabel;
    // End of variables declaration//GEN-END:variables
}
