package view.wizard;

/**
 *
 * @author Neblis
 */
public class WizardDowntowns extends javax.swing.JPanel {

    /**
     * Creates new form WizardDowntowns
     */
    
    private static final String ADD = "Add downtown";
    private static final String DELETE = "Delete downtown";
    
    private final Wizard wizard;
    
    public WizardDowntowns(Wizard wizard) {
        this.wizard = wizard;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDowntown = new javax.swing.JButton();
        deleteDowntown = new javax.swing.JButton();
        downtownList = new javax.swing.JScrollPane();

        addDowntown.setText(ADD);
        addDowntown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDowntownMouseClicked(evt);
            }
        });

        deleteDowntown.setText(DELETE);
        deleteDowntown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteDowntownMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(downtownList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addDowntown, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteDowntown, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addDowntown)
                    .addComponent(deleteDowntown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downtownList, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addDowntownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDowntownMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addDowntownMouseClicked

    private void deleteDowntownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteDowntownMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteDowntownMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDowntown;
    private javax.swing.JButton deleteDowntown;
    private javax.swing.JScrollPane downtownList;
    // End of variables declaration//GEN-END:variables
}
