
package view.mapelements;

import java.awt.Font;
import model.followingmodels.FollowingModel;
import model.followingmodels.IDM;
import model.followingmodels.Kerner;
import model.followingmodels.Krauss;
import model.followingmodels.PW2009;
import model.routes.VType;
import view.C4RView;

/**
 *
 * @author Neblis
 * Krauss / Wagner / Kerner / IDM
 */
public class FollowingModelFrame extends javax.swing.JFrame {

    private final C4RView view;
    private final String name;
    private final VType vehicle;
    
    private Krauss krauss = new Krauss();
    private IDM IDMModel = new IDM();
    private Kerner kerner = new Kerner();
    private PW2009 PW2009 = new PW2009();
    
    private static final String  TITLE = "Set following model";
    private static final String  ACCEPT = "Accept";
    
    private static final String  KRAUSS = "Krauss";
    private static final String  KRAUSS_SIGMA = "Sigma";
    
    private static final String  PWAGNER  = "PWagner2009";
    private static final String  KERNER  = "BKerner";
    private static final String  IDM  = "IDM";
    
    private static final String  MIN_GAP  = "Minimum gap";
    
    private final Font  TITLE_FONT;
    
    /** Creates new form FollowingModelFrame
     * @param view
     * @param name */
    public FollowingModelFrame(C4RView view, String name, VType vehicle) {
        this.view = view;
        this.name = name;
        this.vehicle = vehicle;
        FollowingModel model = vehicle.getModel();
        
        if (model instanceof Krauss){
            krauss = (Krauss)model;
        }else if (model instanceof IDM){
            IDMModel = (IDM) model;
        }else if (model instanceof Kerner){
            kerner = (Kerner) model;
        }else if(model instanceof PW2009){
            PW2009 = (PW2009) model; 
        }
        
        TITLE_FONT = new Font("Century Gothic", Font.BOLD, 16);
        initComponents();
        this.setLocationRelativeTo(view);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        tabPanel = new javax.swing.JTabbedPane();
        kraussPanel = new javax.swing.JPanel();
        kraussMainPanel = new javax.swing.JPanel();
        sigmaLabel = new javax.swing.JLabel();
        minGapLabel = new javax.swing.JLabel();
        sigmaField = new javax.swing.JFormattedTextField();
        minGapField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PWagnerPanel = new javax.swing.JPanel();
        KernerPanel = new javax.swing.JPanel();
        IDMPanel = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setBackground(new java.awt.Color(255, 255, 255));
        titleLabel.setFont(TITLE_FONT);
        titleLabel.setForeground(new java.awt.Color(204, 0, 102));
        titleLabel.setText(TITLE);

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.setBackground(new java.awt.Color(255, 255, 255));

        kraussPanel.setBackground(new java.awt.Color(255, 255, 255));

        kraussMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sigmaLabel.setFont(view.getFont());
        sigmaLabel.setText(KRAUSS_SIGMA);

        minGapLabel.setFont(view.getFont());
        minGapLabel.setText(MIN_GAP);

        sigmaField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        sigmaField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sigmaField.setText(String.valueOf(krauss.getSigma()));
        sigmaField.setFont(view.getFont());

        minGapField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        minGapField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        minGapField.setText(String.valueOf(krauss.getMinGap()));
        minGapField.setFont(view.getFont());

        javax.swing.GroupLayout kraussMainPanelLayout = new javax.swing.GroupLayout(kraussMainPanel);
        kraussMainPanel.setLayout(kraussMainPanelLayout);
        kraussMainPanelLayout.setHorizontalGroup(
            kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kraussMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minGapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sigmaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sigmaField)
                    .addComponent(minGapField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        kraussMainPanelLayout.setVerticalGroup(
            kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kraussMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sigmaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sigmaField))
                .addGap(11, 11, 11)
                .addGroup(kraussMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minGapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minGapField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setFont(view.getFont());
        jTextArea1.setRows(5);
        jTextArea1.setText(Krauss.EXPLANATION);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout kraussPanelLayout = new javax.swing.GroupLayout(kraussPanel);
        kraussPanel.setLayout(kraussPanelLayout);
        kraussPanelLayout.setHorizontalGroup(
            kraussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kraussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kraussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kraussMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kraussPanelLayout.setVerticalGroup(
            kraussPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kraussPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kraussMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanel.addTab(KRAUSS, kraussPanel);

        javax.swing.GroupLayout PWagnerPanelLayout = new javax.swing.GroupLayout(PWagnerPanel);
        PWagnerPanel.setLayout(PWagnerPanelLayout);
        PWagnerPanelLayout.setHorizontalGroup(
            PWagnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        PWagnerPanelLayout.setVerticalGroup(
            PWagnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        tabPanel.addTab(PWAGNER, PWagnerPanel);

        javax.swing.GroupLayout KernerPanelLayout = new javax.swing.GroupLayout(KernerPanel);
        KernerPanel.setLayout(KernerPanelLayout);
        KernerPanelLayout.setHorizontalGroup(
            KernerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        KernerPanelLayout.setVerticalGroup(
            KernerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        tabPanel.addTab(KERNER, KernerPanel);

        javax.swing.GroupLayout IDMPanelLayout = new javax.swing.GroupLayout(IDMPanel);
        IDMPanel.setLayout(IDMPanelLayout);
        IDMPanelLayout.setHorizontalGroup(
            IDMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
        IDMPanelLayout.setVerticalGroup(
            IDMPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        tabPanel.addTab(IDM, IDMPanel);

        acceptButton.setFont(view.getFont());
        acceptButton.setText(ACCEPT);
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acceptButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        System.out.println(tabPanel.getSelectedIndex());
        switch (tabPanel.getSelectedIndex()){
            case 0:
                vehicle.setModel(krauss);
                break;
            case 1:
                vehicle.setModel(PW2009);
                break;
            case 2:
                vehicle.setModel(kerner);
                break;
            case 3:
                vehicle.setModel(IDMModel);
                break;
        }
        view.editVType(name, vehicle);
        this.dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IDMPanel;
    private javax.swing.JPanel KernerPanel;
    private javax.swing.JPanel PWagnerPanel;
    private javax.swing.JButton acceptButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel kraussMainPanel;
    private javax.swing.JPanel kraussPanel;
    private javax.swing.JFormattedTextField minGapField;
    private javax.swing.JLabel minGapLabel;
    private javax.swing.JFormattedTextField sigmaField;
    private javax.swing.JLabel sigmaLabel;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

}
