package view.mapelements;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Neblis
 */
public class MapSystem extends javax.swing.JPanel {

    /**
     * Creates new form MapSystem
     */
    public MapSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void paintComponent(Graphics g){
        g.setColor(Color.RED);
        super.paintComponent(g);
        
        int[] xSin = {1, 20, 30, 40, 50, 60};
        int[] ySin = {1, 20, 30, 40, 50, 60};

        g.drawPolyline(xSin, ySin, xSin.length);
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
