/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mapelements;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;
import view.MogenView;
import view.mapelements.VehicleTypePanel.Icon;

/**
 *
 * @author darkm
 */
public class VTypeIconSelectFrame extends javax.swing.JFrame {
    
    private static final String  TITLE = "Change icon";
    
    VehicleTypePanel panel;
    /**
     * Creates new form VTypeIconSelectFrame
     */
    public VTypeIconSelectFrame(MogenView view, VehicleTypePanel panel) {
        this.panel = panel;
        this.setIconImage(view.getIconImage());
        
        initComponents();
        Border border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GRAY);
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
        
        for(Icon icon: Icon.values()){
            JLabel button = new JLabel();
            
            ImageIcon imageIcon = new ImageIcon(icon.getLocation());
            
            button.setBorder(border);
            button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            button.setPreferredSize(new java.awt.Dimension(Icon.SIZE_X, 
                                                          Icon.SIZE_Y));
            button.setIcon(imageIcon);
            button.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    iconMouseClicked(evt, icon);
                }
            });
            mainPanel.add(button, BorderLayout.NORTH);
        }
        pack();
        setLocationRelativeTo(view);  // centra en ventana principal    
        setVisible(true); 
    }

    private void iconMouseClicked(java.awt.event.MouseEvent evt, Icon icon) {                                  
        // TODO add your handling code here:
        panel.changeIcon(icon);
        this.dispose();
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(TITLE);
        setAlwaysOnTop(true);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
